# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  lane :sprint do

    desc "Push a new --Sprint-- build to TestFlight"
  	xcclean(workspace: "IzifloTemplateTs.xcworkspace", scheme: "IzifloTemplateTs Sprint")
  	cocoapods(
  	  clean_install: true,
  	)
    match(type:"appstore")
    increment_build_number(xcodeproj: "zScan.xcodeproj")
    build_app(workspace: "IzifloTemplateTs.xcworkspace", scheme: "IzifloTemplateTs Sprint")
    upload_to_testflight
  end
  lane :recette do
    desc "Push a new --Recette-- build to TestFlight"
  	xcclean(workspace: "IzifloTemplateTs.xcworkspace", scheme: "IzifloTemplateTs Recette")
  	cocoapods(
  	  clean_install: true,
  	)
    match(type:"appstore")
    increment_build_number(xcodeproj: "zScan.xcodeproj")
    build_app(workspace: "IzifloTemplateTs.xcworkspace", scheme: "IzifloTemplateTs Recette")
    upload_to_testflight
  end
  lane :prod do
    desc "Push a new --Prod-- build to TestFlight"
  	xcclean(workspace: "IzifloTemplateTs.xcworkspace", scheme: "IzifloTemplateTs Prod")
  	cocoapods(
  	  clean_install: true,
  	)
    match(type:"appstore")
    increment_build_number(xcodeproj: "zScan.xcodeproj")
    build_app(workspace: "IzifloTemplateTs.xcworkspace", scheme: "IzifloTemplateTs Prod")
    upload_to_testflight
  end
end
